[tool.poetry]
name = "quant-playground"
version = "0.1.0"
description = ""
authors = ["rukawa917 <chriskang960723@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
